In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.compose import ColumnTransformer

In [2]:
data = pd.read_csv('dirty_cafe_sales.csv')
data.head(n=10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [8]:
# Overview of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4550 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    4550 non-null   object
 1   Item              4550 non-null   object
 2   Quantity          4550 non-null   object
 3   Price Per Unit    4550 non-null   object
 4   Total Spent       4550 non-null   object
 5   Payment Method    4550 non-null   object
 6   Location          4550 non-null   object
 7   Transaction Date  4550 non-null   object
dtypes: object(8)
memory usage: 319.9+ KB

In [9]:
data.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,4550,4550,4550,4550,4550,4550,4550,4550
unique,4550,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,ERROR
freq,1,569,923,1139,464,1443,2041,68

In [3]:
# View unique values of each column, except the Transaction ID column
for col in data.columns[1:-1]:
    print(f'{col}: {data[col].unique()}')

Item: ['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']
Quantity: ['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]
Price Per Unit: ['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']
Total Spent: ['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']
Payment Method: ['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]
Location: ['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']

In [4]:
# View Nans in each column, except the Transaction ID column
for col in data.columns[1:-1]:
    print(f'{col}: {data[col].isna().sum()}')

Item: 333
Quantity: 138
Price Per Unit: 179
Total Spent: 173
Payment Method: 2579
Location: 3265

In [5]:
# Count Error values and UNKOWN values
data[data['Item'] == 'ERROR'].count(), data[data['Item'] == 'UNKNOWN'].count()

(Transaction ID      292
 Item                292
 Quantity            287
 Price Per Unit      285
 Total Spent         285
 Payment Method      213
 Location            197
 Transaction Date    289
 dtype: int64,
 Transaction ID      344
 Item                344
 Quantity            335
 Price Per Unit      337
 Total Spent         336
 Payment Method      256
 Location            223
 Transaction Date    337
 dtype: int64)