In [3]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("HVAC_Dynamic_Fuzzy_PID_2017_with_Target.csv")
data.head(10)

,Timestamp,Temperature_C,Humidity_%,CO2_ppm,Occupancy_Count,External_Temperature_C,Kp,Ki,Kd,Fuzzy_Adjustment_Factor,ISA_Optimization_Score,HVAC_Power_Consumption_kWh,Cooling_Heating_Output_C,Response_Time_s,Energy_Efficiency_%,User_Comfort_Index,HVAC_Efficiency_Class
0,2017-01-01 00:00:00,22.494481,44.945633,983.998649,12,7.752784,2.055758,0.113566,0.448615,0.850555,80.205161,8.944362,0.559912,7.191280,80.040141,8,2
1,2017-01-01 00:10:00,29.408572,43.316484,547.609596,26,14.710904,0.995900,0.205418,0.164713,1.056811,83.156046,3.079141,1.504367,23.742314,97.830274,6,2
2,2017-01-01 00:20:00,26.783927,37.046157,677.311755,37,31.403525,0.863097,0.916411,0.315834,0.991201,52.617556,7.651029,-0.278671,18.729310,93.696734,6,2
3,2017-01-01 00:30:00,25.183902,54.290667,930.624509,32,26.358835,1.077068,0.888923,0.287849,0.809292,66.412146,4.283124,1.569540,5.834288,85.825037,6,2
4,2017-01-01 00:40:00,19.872224,49.064966,785.671476,5,28.574897,2.340311,0.849772,0.492452,1.196332,55.214315,6.757243,0.545708,11.077815,89.098611,6,2
5,2017-01-01 00:50:00,19.871934,64.628040,990.856831,12,28.203026,0.758241,0.735653,0.440258,0.952891,70.841261,7.179767,1.190351,29.190814,85.320522,8,1
6,2017-01-01 01:00:00,18.697003,31.284383,1168.966321,12,8.599173,2.406190,0.695369,0.090944,1.062081,86.363708,8.024928,0.311927,22.996414,81.548969,7,0
7,2017-01-01 01:10:00,28.394114,55.754717,493.237350,12,9.765817,2.489625,0.347964,0.038857,1.193432,90.263607,6.067468,-0.805034,28.100492,90.525703,8,1
8,2017-01-01 01:20:00,25.213380,60.517955,967.654173,19,14.517177,2.066889,0.401495,0.228737,1.053834,88.162259,4.988707,0.259744,18.944285,89.930389,8,1
9,2017-01-01 01:30:00,26.496871,60.379463,584.275325,35,14.030863,2.020845,0.312222,0.277303,0.924661,63.583539,9.562023,0.906862,25.715858,88.889006,8,1

In [ ]:
data.describe()

,Temperature_C,Humidity_%,CO2_ppm,Occupancy_Count,External_Temperature_C,Kp,Ki,Kd,Fuzzy_Adjustment_Factor,ISA_Optimization_Score,HVAC_Power_Consumption_kWh,Cooling_Heating_Output_C,Response_Time_s,Energy_Efficiency_%,User_Comfort_Index,HVAC_Efficiency_Class
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,23.929915,50.181195,800.040316,24.50170,20.055481,1.506866,0.554875,0.253599,1.000385,74.937144,6.020303,0.001047,17.384821,88.992311,7.502800,1.615900
std,3.451562,11.571782,229.419006,14.46958,8.674760,0.575019,0.261304,0.142222,0.114954,14.371408,2.303184,1.154775,7.254648,5.204067,1.121302,0.720707
min,18.000140,30.006310,400.038499,0.00000,5.002798,0.500258,0.100043,0.010056,0.800112,50.016555,2.001831,-1.998841,5.006078,80.000041,6.000000,0.000000
25%,20.955946,40.157832,602.998329,12.00000,12.578841,1.012741,0.330219,0.130712,0.901579,62.384457,4.009593,-1.000384,11.062756,84.510340,6.000000,2.000000
50%,23.910343,50.235871,801.654476,25.00000,20.011469,1.506085,0.552214,0.251956,0.999352,75.098158,6.052887,-0.005172,17.290968,88.978969,8.000000,2.000000
75%,26.880076,60.259169,995.739083,37.00000,27.606939,2.007894,0.786156,0.377335,1.099040,87.284158,7.989601,0.990402,23.719914,93.412954,9.000000,2.000000
max,29.996612,69.996993,1199.920782,49.00000,34.993913,2.499723,0.999906,0.499948,1.199946,99.995599,9.999336,1.998244,29.995145,97.998844,9.000000,2.000000

In [6]:
# Convert to relative time measurement from the t0, format YYYY-MM-DD HH:mm:ss.######
data["Timestamp"] = pd.to_datetime(
    data["Timestamp"],
    format="%Y-%m-%d %H:%M:%S"
)

t0 = data["Timestamp"].iloc[0]
data["time_seconds"] = (data["Timestamp"] - t0).dt.total_seconds().astype(int)
data = data.drop(columns=['Timestamp'])
data.head(10)

,Temperature_C,Humidity_%,CO2_ppm,Occupancy_Count,External_Temperature_C,Kp,Ki,Kd,Fuzzy_Adjustment_Factor,ISA_Optimization_Score,HVAC_Power_Consumption_kWh,Cooling_Heating_Output_C,Response_Time_s,Energy_Efficiency_%,User_Comfort_Index,HVAC_Efficiency_Class,time_seconds
0,22.494481,44.945633,983.998649,12,7.752784,2.055758,0.113566,0.448615,0.850555,80.205161,8.944362,0.559912,7.191280,80.040141,8,2,0
1,29.408572,43.316484,547.609596,26,14.710904,0.995900,0.205418,0.164713,1.056811,83.156046,3.079141,1.504367,23.742314,97.830274,6,2,600
2,26.783927,37.046157,677.311755,37,31.403525,0.863097,0.916411,0.315834,0.991201,52.617556,7.651029,-0.278671,18.729310,93.696734,6,2,1200
3,25.183902,54.290667,930.624509,32,26.358835,1.077068,0.888923,0.287849,0.809292,66.412146,4.283124,1.569540,5.834288,85.825037,6,2,1800
4,19.872224,49.064966,785.671476,5,28.574897,2.340311,0.849772,0.492452,1.196332,55.214315,6.757243,0.545708,11.077815,89.098611,6,2,2400
5,19.871934,64.628040,990.856831,12,28.203026,0.758241,0.735653,0.440258,0.952891,70.841261,7.179767,1.190351,29.190814,85.320522,8,1,3000
6,18.697003,31.284383,1168.966321,12,8.599173,2.406190,0.695369,0.090944,1.062081,86.363708,8.024928,0.311927,22.996414,81.548969,7,0,3600
7,28.394114,55.754717,493.237350,12,9.765817,2.489625,0.347964,0.038857,1.193432,90.263607,6.067468,-0.805034,28.100492,90.525703,8,1,4200
8,25.213380,60.517955,967.654173,19,14.517177,2.066889,0.401495,0.228737,1.053834,88.162259,4.988707,0.259744,18.944285,89.930389,8,1,4800
9,26.496871,60.379463,584.275325,35,14.030863,2.020845,0.312222,0.277303,0.924661,63.583539,9.562023,0.906862,25.715858,88.889006,8,1,5400