In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("industrial_robot_control_6G_network.csv")
data.head(10)

,robot_id,task_type,task_duration,energy_consumption,position_coordinates,robot_speed,sensor_id,sensor_type,sensor_reading,timestamp,...,slice_id,slice_bandwidth,command_delay,feedback_delay,data_transfer_time,total_delay,signal_strength,latency,resource_allocation,error_rate
0,R001,Pick-and-Place,171.516018,4.733739,"(7.796910002727692, 5.96850157946487, 4.458327...",0.509972,S8,Temperature,88.033450,2025-01-21 10:00:00,...,Slice2,1755,7.751068,16.084845,20.495129,51.490766,-61.263126,14.177793,82.092408,0.292145
1,R002,Pick-and-Place,123.849798,7.140704,"(1.9967378215835974, 5.142344384136116, 5.9241...",0.451095,S3,Motion,75.115724,2025-01-21 10:01:00,...,Slice1,1364,8.463407,14.820509,23.665270,54.999170,-45.004153,7.600470,85.865909,0.182236
2,R003,Assembly,119.521822,4.831767,"(5.677003278199915, 0.31313292455558583, 8.422...",0.894730,S4,Pressure,91.818160,2025-01-21 10:02:00,...,Slice4,1137,13.095382,21.735023,29.305106,72.170683,-61.720025,9.444103,82.479004,0.015636
3,R004,Welding,168.114268,4.794863,"(0.05522117123602399, 8.154614284548341, 7.068...",1.201908,S1,Motion,72.221340,2025-01-21 10:03:00,...,Slice1,1871,10.562274,23.376825,23.318447,65.214035,-61.758346,13.418651,85.743903,0.971712
4,R005,Pick-and-Place,166.509907,6.245109,"(7.70967179954561, 4.937955963643907, 5.227328...",0.870295,S3,Motion,96.872908,2025-01-21 10:04:00,...,Slice3,1548,13.097616,14.061224,28.857071,64.010240,-49.156452,18.207018,89.365311,0.295634
5,R006,Welding,182.004483,7.214688,"(1.8657005888603584, 8.925589984899778, 5.3934...",1.288184,S9,Motion,97.204853,2025-01-21 10:05:00,...,Slice3,1509,12.661210,18.348220,14.442156,51.050913,-59.871545,19.143646,84.848044,0.518791
6,R007,Welding,116.537064,4.259569,"(2.539154139343447, 2.468760628386012, 6.96304...",1.183498,S5,Temperature,99.932215,2025-01-21 10:06:00,...,Slice4,1184,8.593428,12.897897,19.789055,51.208633,-62.738342,15.082033,91.424294,0.237638
7,R008,Pick-and-Place,172.439566,5.881203,"(9.83423140894843, 3.9882444244455306, 8.16431...",1.278180,S9,Motion,75.595555,2025-01-21 10:07:00,...,Slice3,946,10.229990,11.923531,28.810465,57.951846,-54.467459,17.565652,90.135352,0.735216
8,R009,Assembly,189.457107,7.509357,"(2.579416277151556, 6.59984046034179, 8.172222...",1.010721,S1,Pressure,99.887611,2025-01-21 10:08:00,...,Slice1,1922,15.505367,26.933223,27.126486,76.587617,-43.366897,17.763927,94.034525,0.785341
9,R010,Assembly,61.287587,4.405886,"(6.635017691080558, 0.05061583846218687, 1.608...",1.003607,S6,Motion,89.558838,2025-01-21 10:09:00,...,Slice3,1200,9.620912,20.850805,20.176282,58.829661,-62.486145,13.848063,94.683393,0.486742

In [3]:
data.describe()

,task_duration,energy_consumption,robot_speed,sensor_reading,data_size,network_load,network_latency,packet_loss_rate,slice_bandwidth,command_delay,feedback_delay,data_transfer_time,total_delay,signal_strength,latency,resource_allocation,error_rate
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,127.988959,6.042381,0.953004,85.177590,1271.007000,82.506728,12.683209,2.478404,1398.906000,12.502624,19.968831,20.051832,60.107442,-55.027301,12.362544,87.373984,0.491221
std,40.548998,1.187298,0.315788,8.714482,449.566011,7.346952,4.360068,1.446064,356.111762,4.284195,5.680520,5.867813,9.255278,8.555075,4.336256,4.364712,0.290525
min,60.034011,4.004118,0.402935,70.005596,513.000000,70.029092,5.009801,0.003739,801.000000,5.020333,10.001057,10.031302,33.765475,-69.934476,5.003615,80.000175,0.000286
25%,92.221514,5.003544,0.681001,77.601717,883.750000,76.173751,8.973807,1.229622,1077.500000,8.850182,15.004031,14.918942,53.661210,-62.493750,8.560218,83.602383,0.235013
50%,125.999767,6.118209,0.957400,85.334433,1266.500000,82.401671,12.823581,2.415215,1383.500000,12.544205,19.861459,20.095154,59.755662,-54.824600,12.231999,87.209757,0.479584
75%,163.055834,7.097753,1.223109,92.324701,1647.250000,88.817923,16.629854,3.776907,1713.000000,16.145204,24.804142,25.142245,66.450606,-47.568047,16.092120,91.094122,0.753804
max,199.678216,7.997340,1.498910,99.967141,2047.000000,94.987953,19.988691,4.998706,1999.000000,19.995045,29.993897,29.986726,87.054346,-40.005498,19.992578,94.998515,0.995780