In [6]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("intelligent_streetlight_dataset.csv")
data.head(10)

,Timestamp,Street ID,Day/Night,Traffic Count,Traffic Density,Traffic Speed,Ambient Light (lux),Weather,Energy Consumption (kWh),Power State,Dim Level,Latitude,Longitude,Special Event,Holiday/Weekend
0,2024-01-21 05:27:00,8,Day,154,41.750173,59.383884,172.439065,Clear,0.37,1,50,40.877092,-73.813538,1,0
1,2024-01-11 12:15:00,3,Night,103,30.949961,24.208586,189.339042,Rainy,0.00,0,100,40.862553,-74.125943,0,0
2,2024-01-29 20:18:00,9,Night,203,32.089607,29.733312,200.236036,Cloudy,0.00,0,75,40.809826,-73.853724,1,0
3,2024-01-05 13:42:00,5,Day,161,27.758249,27.850047,197.078404,Cloudy,0.78,1,100,40.529601,-74.073302,0,0
4,2024-01-08 07:45:00,1,Night,55,41.492456,59.282133,279.109775,Clear,0.46,1,50,40.565817,-74.116742,1,1
5,2024-01-26 17:13:00,6,Night,200,28.293919,23.986351,226.654123,Cloudy,0.83,1,100,40.728570,-73.859139,0,0
6,2024-01-15 17:21:00,2,Day,244,26.971331,48.980259,137.154322,Clear,0.00,0,50,40.751900,-73.771091,0,0
7,2024-01-12 04:06:00,6,Day,228,16.025011,46.700969,34.368789,Cloudy,0.43,1,100,40.552163,-74.166822,1,0
8,2024-01-10 17:16:00,1,Day,51,31.692600,58.172359,85.197577,Clear,0.00,0,75,40.569960,-73.884714,0,0
9,2024-01-23 08:54:00,1,Day,81,55.383021,47.332112,66.610264,Clear,0.00,0,100,40.603965,-74.059541,0,1

In [7]:
data.describe()

,Street ID,Traffic Count,Traffic Density,Traffic Speed,Ambient Light (lux),Energy Consumption (kWh),Power State,Dim Level,Latitude,Longitude,Special Event,Holiday/Weekend
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,5.508000,177.429000,35.047700,39.891310,171.234179,0.241780,0.503000,49.225000,40.702442,-73.946743,0.459000,0.498000
std,2.909364,70.064756,14.647251,11.603187,101.865321,0.291477,0.500241,35.969684,0.115534,0.142642,0.498566,0.500246
min,1.000000,50.000000,10.073398,20.036734,0.078170,0.000000,0.000000,0.000000,40.500899,-74.198446,0.000000,0.000000
25%,3.000000,118.000000,22.296820,29.682256,81.068828,0.000000,0.000000,25.000000,40.605432,-74.072035,0.000000,0.000000
50%,5.000000,179.000000,35.566512,39.294904,167.424778,0.075000,1.000000,50.000000,40.704036,-73.939872,0.000000,0.000000
75%,8.000000,237.250000,47.676395,49.999874,255.746741,0.460000,1.000000,75.000000,40.803821,-73.823415,1.000000,1.000000
max,10.000000,299.000000,59.993186,59.993270,349.747146,1.360000,1.000000,100.000000,40.899189,-73.700907,1.000000,1.000000

In [10]:
# Convert to relative time measurement from the t0, format YYYY-MM-DD HH:mm:ss.######
data["Timestamp"] = pd.to_datetime(
    data["Timestamp"],
    format="%Y-%m-%d %H:%M:%S"
)
data = data.sort_values(['Timestamp'])

t0 = data["Timestamp"].iloc[0]
data["time_seconds"] = (data["Timestamp"] - t0).dt.total_seconds().astype(int)
data.head(10)

,Timestamp,Street ID,Day/Night,Traffic Count,Traffic Density,Traffic Speed,Ambient Light (lux),Weather,Energy Consumption (kWh),Power State,Dim Level,Latitude,Longitude,Special Event,Holiday/Weekend,time_seconds
888,2024-01-01 00:13:00,4,Day,138,13.598167,42.184218,279.524143,Cloudy,0.00,0,75,40.629837,-74.021929,0,0,0
171,2024-01-01 00:21:00,6,Night,245,43.463640,23.873559,232.828946,Cloudy,0.90,1,100,40.649818,-74.032941,1,0,480
586,2024-01-01 00:27:00,6,Night,96,46.103635,32.763675,68.878547,Rainy,0.18,1,75,40.897741,-73.939575,1,0,840
360,2024-01-01 01:12:00,1,Night,211,45.825175,41.935423,172.657189,Clear,0.83,1,100,40.813486,-73.704274,1,0,3540
849,2024-01-01 01:16:00,2,Night,262,12.700400,37.043547,265.588667,Clear,0.00,0,100,40.842534,-74.127582,1,0,3780
152,2024-01-01 02:01:00,1,Day,55,28.241318,33.270998,276.910703,Rainy,0.00,0,0,40.709789,-73.959275,1,0,6480
180,2024-01-01 02:58:00,2,Night,147,29.174147,46.317485,7.878488,Cloudy,0.00,0,75,40.809281,-73.832620,0,0,9900
43,2024-01-01 03:00:00,7,Night,229,25.151012,30.863811,205.705168,Cloudy,0.55,1,75,40.856372,-73.880830,1,0,10020
199,2024-01-01 04:17:00,5,Night,153,30.793542,53.842745,218.676551,Clear,0.44,1,75,40.645602,-73.838843,1,1,14640
540,2024-01-01 04:29:00,6,Night,174,18.032232,26.963304,223.167569,Clear,0.00,0,50,40.693682,-73.977515,1,0,15360