In [3]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("intelligent_indoor_environment_dataset.csv")
data.head(10)

,timestamp,room_temperature,room_humidity,lighting_intensity,room_air_quality,room_CO2,room_occupancy,occupant_id,lighting_control,HVAC_temperature,air_quality_control,energy_consumption,energy_cost,predicted_entry_time,predicted_exit_time,energy_efficiency
0,2024-02-05 08:00:00,21.872701,37.776994,204.682273,53.454060,407.199588,0,2,43.211624,21.417536,1.795786,1.320293,0.158435,7,9,1
1,2024-02-05 08:15:00,24.753572,43.128514,198.791520,55.933628,430.543233,1,3,96.659077,24.742126,7.451046,0.904110,0.108493,4,8,0
2,2024-02-05 08:30:00,23.659970,48.094188,462.501832,45.009358,426.016093,0,8,45.221510,24.212321,51.039272,0.721501,0.086580,14,1,0
3,2024-02-05 08:45:00,22.993292,45.983373,199.818480,52.497482,365.389990,1,7,14.278564,23.611868,96.943938,1.012023,0.121443,14,10,1
4,2024-02-05 09:00:00,20.780093,47.098417,208.779890,51.434920,364.924947,1,2,38.943468,20.389969,69.320954,1.048842,0.125861,6,12,1
5,2024-02-05 09:15:00,20.779973,44.881751,403.759305,56.656608,376.817437,0,6,95.170241,20.530650,7.091619,1.038326,0.124599,7,9,1
6,2024-02-05 09:30:00,20.290418,45.384148,279.895937,58.121741,386.107473,1,9,31.972085,22.463907,18.936088,1.065074,0.127809,11,2,1
7,2024-02-05 09:45:00,24.330881,47.737935,410.684223,40.243135,390.845558,1,4,86.809816,20.803567,77.132314,1.448705,0.173845,6,3,1
8,2024-02-05 10:00:00,23.005575,38.745020,126.146463,53.480398,417.969722,0,9,88.125068,24.891327,84.143976,1.402246,0.168269,11,2,1
9,2024-02-05 10:15:00,23.540363,42.341374,295.028477,41.036716,355.668043,0,2,35.018652,20.792601,61.769459,1.375717,0.165086,13,13,1

In [4]:
data.describe()

,room_temperature,room_humidity,lighting_intensity,room_air_quality,room_CO2,room_occupancy,occupant_id,lighting_control,HVAC_temperature,air_quality_control,energy_consumption,energy_cost,predicted_entry_time,predicted_exit_time,energy_efficiency
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,22.451283,42.605260,300.962290,49.807501,399.410532,0.511000,5.494000,49.616712,22.398411,49.220629,0.992631,0.119116,7.556000,7.380000,0.49000
std,1.460687,4.382848,116.269678,5.729787,28.680994,0.500129,2.904548,28.825466,1.422380,28.029718,0.285682,0.034282,3.962394,4.102247,0.50015
min,20.023160,35.048274,100.004654,40.013068,350.003072,0.000000,1.000000,0.024100,20.001215,0.005283,0.500241,0.060029,1.000000,1.000000,0.00000
25%,21.179866,38.616114,204.540391,44.838015,374.497401,0.000000,3.000000,24.772508,21.171887,25.818315,0.745941,0.089513,4.000000,4.000000,0.00000
50%,22.484037,42.781009,300.245568,49.685586,399.459810,1.000000,5.000000,48.516983,22.349906,48.853656,0.993272,0.119193,8.000000,7.000000,0.00000
75%,23.721598,46.406976,403.641411,54.750816,423.999345,1.000000,8.000000,75.528842,23.538145,72.178677,1.238852,0.148662,11.000000,11.000000,1.00000
max,24.998588,49.991206,499.128342,59.991154,449.774939,1.000000,10.000000,99.920730,24.994523,99.699050,1.499505,0.179941,14.000000,14.000000,1.00000

In [5]:
# Convert to relative time measurement from the t0, format YYYY-MM-DD HH:mm:ss.######
data["timestamp"] = pd.to_datetime(
    data["timestamp"],
    format="%Y-%m-%d %H:%M:%S"
)

t0 = data["timestamp"].iloc[0]
data["time_seconds"] = (data["timestamp"] - t0).dt.total_seconds().astype(int)
data = data.drop(columns=['timestamp'])
data.head(10)

,room_temperature,room_humidity,lighting_intensity,room_air_quality,room_CO2,room_occupancy,occupant_id,lighting_control,HVAC_temperature,air_quality_control,energy_consumption,energy_cost,predicted_entry_time,predicted_exit_time,energy_efficiency,time_seconds
0,21.872701,37.776994,204.682273,53.454060,407.199588,0,2,43.211624,21.417536,1.795786,1.320293,0.158435,7,9,1,0
1,24.753572,43.128514,198.791520,55.933628,430.543233,1,3,96.659077,24.742126,7.451046,0.904110,0.108493,4,8,0,900
2,23.659970,48.094188,462.501832,45.009358,426.016093,0,8,45.221510,24.212321,51.039272,0.721501,0.086580,14,1,0,1800
3,22.993292,45.983373,199.818480,52.497482,365.389990,1,7,14.278564,23.611868,96.943938,1.012023,0.121443,14,10,1,2700
4,20.780093,47.098417,208.779890,51.434920,364.924947,1,2,38.943468,20.389969,69.320954,1.048842,0.125861,6,12,1,3600
5,20.779973,44.881751,403.759305,56.656608,376.817437,0,6,95.170241,20.530650,7.091619,1.038326,0.124599,7,9,1,4500
6,20.290418,45.384148,279.895937,58.121741,386.107473,1,9,31.972085,22.463907,18.936088,1.065074,0.127809,11,2,1,5400
7,24.330881,47.737935,410.684223,40.243135,390.845558,1,4,86.809816,20.803567,77.132314,1.448705,0.173845,6,3,1,6300
8,23.005575,38.745020,126.146463,53.480398,417.969722,0,9,88.125068,24.891327,84.143976,1.402246,0.168269,11,2,1,7200
9,23.540363,42.341374,295.028477,41.036716,355.668043,0,2,35.018652,20.792601,61.769459,1.375717,0.165086,13,13,1,8100